---
title: "Stations / Sensors Reporting Check"
author: "Eric R. Scott"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(blastula)
library(azmetr)
library(dplyr)
library(tidyr)
```

## Check for missing stations

```{r}
daily <- az_daily()

st_miss <- setdiff(station_info$meta_station_name, unique(daily$meta_station_name))
all_st_report <- length(st_miss) == 0
st_miss
```

## Check for missing data

```{r}
sen_miss <- 
  daily |> 
  #these will always be NA since these stations don't have soil probes
  mutate(across(
    starts_with("temp_soil"),
    \(x) ifelse(meta_station_id %in% c("az28", "az40", "az42", "az43", "az44"), 0, x)
  )) |>
  #these will always be NA since there is no rain gauge there
  mutate(across(
    starts_with("precip_"),
    \(x) ifelse(meta_station_id %in% c("az42", "az43"), 0, x)
  )) |>
  filter(if_any(where(is.numeric), is.na)) |> 
  select(meta_station_id, meta_station_name, datetime, where(\(x) any(is.na(x)))) 



all_sen_report <- nrow(sen_miss) == 0
sen_miss
```

## Condition to suppress report

```{r}
if (all_sen_report & all_st_report) {
  suppress_scheduled_email()
} else {
  render_connect_email(input = "report_email.Rmd") |> 
    attach_connect_email(subject = "Alert: AZMet stations not reporting")
}
```

