#This works, but it only works *locally*.  Will not work if run by a shiny app or GitHub actions because it requires interactive authentication
library(Microsoft365R)

outlb <- get_business_outlook() #opens a web page and prompts authentication first time ran

# compose an email with blastula
library(blastula)
bl_body <- "## Hello!

This is an email message that was generated by the blastula package.

We can use **Markdown** formatting with the `md()` function.

Cheers,

The blastula team"

bl_em <- compose_email(
  body=md(bl_body),
  footer=md("sent via Microsoft365R")
)
em <- outlb$create_email(bl_em, subject="Hello from R", to="scottericr@gmail.com")
em$send()
